name: From Slack Upload

on:
  workflow_dispatch:
    inputs:
      uuid:
        required: true
      pr_number:
        required: true
      branch:
        required: true
      action:
        required: true

jobs:
  handle-click-upload-button:
    runs-on: ubuntu-latest
    env:
      SHEET_API_TOKEN: ${{ secrets.SHEET_API_TOKEN }}
    steps:
      - name: Get inputs
        id: inputs
        run: |
          ACTION="${{ github.event.inputs.action }}"
          UUID="${{ github.event.inputs.uuid }}"
          BRANCH="${{ github.event.inputs.branch }}"
          PR_NUMBER="${{ github.event.inputs.pr_number }}"
          echo "action=$ACTION" >> $GITHUB_OUTPUT
          echo "uuid=$UUID" >> $GITHUB_OUTPUT
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT

      - name: Log (inputs and resubmit URL)
        run: |
          echo "Action: ${{ steps.inputs.outputs.action }}"
          echo "UUID: ${{ steps.inputs.outputs.uuid }}"
          echo "Branch: ${{ steps.inputs.outputs.branch }}"
          echo "PR number: ${{ steps.inputs.outputs.pr_number }}"
